import Provider from "@/Provider/Provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ToastProvider from "@/Provider/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rounders",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="overflow-x-hidden ">
      <body className="max-w-md lg:max-w-full bg-black overflow-x-hidden  relative">
        <Provider>{children}</Provider>
        <ToastProvider />
      </body>
    </html>
  );
}
